# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-19 23:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.IntegerField(db_column='user_id', primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=20)),
                ('userPwd', models.CharField(max_length=40)),
                ('userEmail', models.CharField(max_length=30)),
                ('userAddress', models.CharField(default='', max_length=100)),
                ('userTel', models.CharField(default='', max_length=11)),
                ('Account', models.IntegerField(default=0)),
                ('img_path', models.CharField(default='/static/img/touxiang.jpg', max_length=100)),
                ('qianming', models.CharField(default='', max_length=100)),
                ('img', models.ImageField(default='static/img/111.jpg', upload_to='img')),
                ('imgname', models.CharField(default='null', max_length=20)),
                ('sex', models.IntegerField(default=0)),
                ('jianjie', models.TextField(default='null')),
                ('create_date', models.DateTimeField(db_column='user_create_date', default=datetime.datetime.utcnow)),
            ],
            options={
                'db_table': 'zw_user',
            },
        ),
    ]
