# Generated by Django 2.1.1 on 2018-08-31 09:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('test_shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('0a8233df-9f3e-4884-b71f-cde05e380cc4')),
        ),
        migrations.AddField(
            model_name='authordetail',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('fce27c55-112b-4145-8ba1-98047be2879c')),
        ),
        migrations.AddField(
            model_name='book',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('09068c92-f4b1-496c-a35d-26d69139dd97')),
        ),
        migrations.AddField(
            model_name='publisher',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('b7ba8453-4614-4399-9c3c-ee40e53855f4')),
        ),
    ]
