# Generated by Django 2.1.1 on 2018-08-31 10:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('test_shop', '0002_auto_20180831_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='phone',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='author',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('0d16911c-fd66-46c3-98ea-527b9f8073f6')),
        ),
        migrations.AlterField(
            model_name='authordetail',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('a7b698b9-f872-445e-ad0d-8d86e9b8989c')),
        ),
        migrations.AlterField(
            model_name='book',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('3db38cc9-c550-43a3-b756-9159eadfda2f')),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('ae947155-09f8-49eb-b490-d9e4c444f1c5')),
        ),
    ]
